name: 'terraform-plan-approve-apply'
description: 'Common workflow for Terraform'
inputs:
  working-directory:
    description: 'Working directory for this action'
    required: false
    default: '.'
outputs:
  fmt:
    description: "Status of terraform format"
    value: ${{ steps.fmt.outputs.test }}
  init:
    description: "Status of terraform init"
    value: ${{ steps.init.outputs.test }}
  validate:
    description: "Status of terraform validate"
    value: ${{ steps.validate.outputs.test }}

runs:
  using: "composite"
  steps:
    - name: Goodbye Script
      run: ${{ github.action_path }}/goodbye.sh
      shell: bash

    - name: Terraform Format
      id: fmt
      run: if terraform fmt -check; then echo "::set-output name=test::success"; else echo "::set-output name=test::fail"; fi
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - name: Terraform Init
      id: init
      run: if terraform init -input=false; then echo "::set-output name=test::success"; else echo "::set-output name=test::fail"; fi
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - name: Terraform Validate
      id: validate
      run: |
        if terraform validate -no-color; then
        echo "::set-output name=test::success"
        else
        echo "::set-output name=test::fail"
        fi
      shell: bash
      working-directory: ${{ inputs.working-directory }}
